const TOKEN_KEY = 'token';

export default {
        token: localStorage.getItem(TOKEN_KEY) || null,
        isAuthenticated: false,
        etape: 1,
        mode: '',
        erreur:'',
        loading: false,
        success: false,
        panier: [],
        mesCommandesSession: JSON.parse(sessionStorage.getItem('mesCommandes')) || [],
        lastKnownClientEmail: localStorage.getItem('lastKnownClientEmail') || null,
        lastKnownClientName: localStorage.getItem('lastKnownClientName') || null,
        selectedImage: null,
        userData: null,
        articles: null,
        article: null,
        membre: null,
        demandes: null,
        conges : null,
        conge: null,
        clients : null,
        client : null,
        variations: null,
        variations2: null,
        checklists: null,
        checklist: null,
        personnel:null,
        favoris: null,
        demande: null,
        produitT: null,
        videos: '',
        uploadProgress: 0,
        panierPrix: '',
        ca:'',
		cam:'',
		totalp:'',
		totalco:'',
		totalca:'',
        taches: null,
        logs: null,
        mesTaches: null,
        tache: null,
        admins: null,
        code:'UNDEFINED',
        stats:[],
        stats2:[],
        statsTresor:[],
        statsFiltres: {},
        statsTresorFiltres: {},
        promo:'',
        transactions:[],
        transferts:[],
        transaction: null,
        menus: null,
        menu: null,
        factures: null,
        facture: null,
        commandes: null,
        commande: null,
        reservations: null,
        reservations2: null,
        reservation: null,
        promos: null,
        dynamicPages: [],
        faqs: null,
        annonce: null,
};
